// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCW8PZQymaNfQXZzDboTLbjYGbvw4J-hRM',
    appId: '1:161626369553:web:ab495042860ea7ad38cbb0',
    messagingSenderId: '161626369553',
    projectId: 'twitter-clone-app-d00ad',
    authDomain: 'twitter-clone-app-d00ad.firebaseapp.com',
    storageBucket: 'twitter-clone-app-d00ad.appspot.com',
    measurementId: 'G-2B7EFCHLTH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAeHZVSH5U8DW8vtCooRd-gWY05dXns78',
    appId: '1:161626369553:android:9c5a3c4eee826bbd38cbb0',
    messagingSenderId: '161626369553',
    projectId: 'twitter-clone-app-d00ad',
    storageBucket: 'twitter-clone-app-d00ad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB52mdRFJ3u1l9y7B_UTorH-_Kt3bCyyS8',
    appId: '1:161626369553:ios:7bf01c3e9441894938cbb0',
    messagingSenderId: '161626369553',
    projectId: 'twitter-clone-app-d00ad',
    storageBucket: 'twitter-clone-app-d00ad.appspot.com',
    iosBundleId: 'com.example.twitterclone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB52mdRFJ3u1l9y7B_UTorH-_Kt3bCyyS8',
    appId: '1:161626369553:ios:708ca6a85f17dcc138cbb0',
    messagingSenderId: '161626369553',
    projectId: 'twitter-clone-app-d00ad',
    storageBucket: 'twitter-clone-app-d00ad.appspot.com',
    iosBundleId: 'com.example.twitterclone.RunnerTests',
  );
}
